In [18]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1
l0 = X
for iter in range(10000):

    # forward propagation
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print("Output After Training:")
print(l1)


Output After Training:
[[ 0.00966449]
 [ 0.00786506]
 [ 0.99358898]
 [ 0.99211957]]


In [16]:
l0 = X

syn0 = 2*np.random.random((3,1)) - 1
syn0



array([[ 0.7527783 ],
       [ 0.78921333],
       [-0.82991158]])

In [17]:
np.dot(l0,syn0)

array([[-0.82991158],
       [-0.04069825],
       [-0.07713327],
       [ 0.71208005]])

In [7]:
2*np.random.random((3,1))
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [8]:
range(8)
list(range(8))

[0, 1, 2, 3, 4, 5, 6, 7]